#!/bin/bash
# Generate .env file from Terraform outputs.
# Run from the terraform/ directory after 'terraform apply'.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

SERVER_IP=$(terraform -chdir="$SCRIPT_DIR" output -raw server_ip 2>/dev/null)

if [ -z "$SERVER_IP" ]; then
    echo "Error: Could not get server_ip from terraform output."
    echo "Make sure you've run 'terraform apply' first."
    exit 1
fi

SSH_KEY=$(terraform -chdir="$SCRIPT_DIR" output -json env_file_content 2>/dev/null | \
    python3 -c "import sys,json; print(json.load(sys.stdin))" | \
    grep LAB_SSH_KEY | awk -F= '{print $2}')

cat > "$ENV_FILE" <<EOF
# Auto-generated by terraform/generate-env.sh
LAB_HOST=${SERVER_IP}
LAB_USER=root
LAB_SSH_KEY=${SSH_KEY:-~/.ssh/id_ed25519}
LAB_PORT=22
LAB_REMOTE_DIR=/opt/containerlab
LAB_VENDOR=srlinux
EOF

echo "Generated $ENV_FILE with LAB_HOST=${SERVER_IP}"
echo "You can now run: ./scripts/lab deploy"
