frr version 8.5
frr defaults traditional
hostname leaf1
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.11/32
!
interface eth1
 description Link to spine1 eth1
 ip address 10.1.1.1/31
!
interface eth2
 description Link to spine2 eth1
 ip address 10.2.1.1/31
!
interface eth3
 description Link to client1
 ip address 10.10.1.1/24
!
interface eth4
 description Link to client2
 ip address 10.10.1.1/24
!
router bgp 65011
 bgp router-id 10.0.0.11
 neighbor 10.1.1.0 remote-as 65001
 neighbor 10.1.1.0 description spine1
 neighbor 10.2.1.0 remote-as 65002
 neighbor 10.2.1.0 description spine2
 !
 address-family ipv4 unicast
  network 10.0.0.11/32
  network 10.10.1.0/24
  neighbor 10.1.1.0 activate
  neighbor 10.2.1.0 activate
 exit-address-family
!
line vty
!
