frr version 8.5
frr defaults traditional
hostname leaf2
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.12/32
!
interface eth1
 description Link to spine1 eth2
 ip address 10.1.2.1/31
!
interface eth2
 description Link to spine2 eth2
 ip address 10.2.2.1/31
!
interface eth3
 description Link to client3
 ip address 10.10.2.1/24
!
interface eth4
 description Link to client4
 ip address 10.10.2.1/24
!
router bgp 65012
 bgp router-id 10.0.0.12
 neighbor 10.1.2.0 remote-as 65001
 neighbor 10.1.2.0 description spine1
 neighbor 10.2.2.0 remote-as 65002
 neighbor 10.2.2.0 description spine2
 !
 address-family ipv4 unicast
  network 10.0.0.12/32
  network 10.10.2.0/24
  neighbor 10.1.2.0 activate
  neighbor 10.2.2.0 activate
 exit-address-family
!
line vty
!
