frr version 8.5
frr defaults traditional
hostname leaf3
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.13/32
!
interface eth1
 description Link to spine1 eth3
 ip address 10.1.3.1/31
!
interface eth2
 description Link to spine2 eth3
 ip address 10.2.3.1/31
!
interface eth3
 description Link to client5
 ip address 10.10.3.1/24
!
interface eth4
 description Link to client6
 ip address 10.10.3.1/24
!
router bgp 65013
 bgp router-id 10.0.0.13
 neighbor 10.1.3.0 remote-as 65001
 neighbor 10.1.3.0 description spine1
 neighbor 10.2.3.0 remote-as 65002
 neighbor 10.2.3.0 description spine2
 !
 address-family ipv4 unicast
  network 10.0.0.13/32
  network 10.10.3.0/24
  neighbor 10.1.3.0 activate
  neighbor 10.2.3.0 activate
 exit-address-family
!
line vty
!
